### ISSUE TITLE
Error when controller is not tracking

### ISSUE THREAD

**Issue by valentin-pinkau** [msfeldstein/three-vive-controller#2]
Hey,
if the vive controller is not tracked anymore an error occurs:
Uncaught TypeError: Cannot read property '0' of null...

Position and Rotation of the pose are null.

I would like to fix this. My approach would be to save the last available values and use these if the tracking fails instead.

**Comment by msfeldstein** [comment]
Cool I can take a look this weekend but if you want to make a pull request
that works too
